### ISSUE TITLE
Further information potential references ANDS workshops

### ISSUE THREAD

**Issue by MonicaDuke** [alex-ball/HowTo-CiteDatasets#14]
ANDS data citation workshops
9 Apr 2014, Canberra
Data Citation and DOIs Overview [PPT 11MB]
Data Citation in CSIRO [PPT 733KB]
Data Citation in GeoScience Australia [PPT 4MB]
Is "publish or perish" now "visible or vanish"?, Ginny Barbour, PLOS [PPT 2.4MB]

20 Mar 2014, Perth
Data Citation Overview [PPT 11MB]
Data Citation & DOIs [PPT 1.01MB]
Data Citation in CSIRO - Sue Cook [PPT 762KB]
Data Citation at Griffith University - Sam Searle, Natasha Simons [PPT 3.52]
Griffith University Data Citation poster [535 KB]
Data Citation Rewards [PPT 5.43MB]

**Comment by MonicaDuke** [comment]
14 March 2014, Adelaide
Adelaide: Building a culture of data citation

Data citation overview - Gerry Ryder [PPT 11 MB]
Data citation and DOIs - Karen Visser [PPT 1010 MB]
DOIs at TERN EcoInformatics - Martin Pullan [PPT 1.21 MB]
Data citation at CSIRO - David Benn [PPT 759 KB]
Where are the rewards? - Gerry Ryder [PPT 5.15 MB]
Data citation at Flinders University - Amanda Nixon [PPT 3.95 MB]

29 Jan 2014 Victoria
Victorian Data Citation workshop

Data Citation Overview [PPT 10MB]
Data Citation and DOIs [PPT 581KB]
Data Citation Rewards [PPT 5.43MB]
Data Citation at Deakin - C. McAvaney [PPT 143 KB]
Data Citation at Deakin - A. Moloney [PPT 387 KB]
Data Citation at CSIRO [705 KB]

Links available from http://ands.org.au/presentations/index.html

6 Nov 2013
Sydney Data Citers catchup

Overview and update [PPT 7.44MB ]
Data Citation and DOIs [PPT 629KB]
ANDS and Data Citation [PPT 2.68MB]
Data Citation at UNSW [PPT 7.27MB]
Data Citation in CSIRO [PPT 743KB]

**Comment by alex-ball** [comment]
This is quite a diffuse set of resources, and therefore not easy to recommend to the readers, especially as there is some overlap within the set and with other resources already recommended or referenced.

Perhaps individual presentations might be included if the need arises in future editions.
