### ISSUE TITLE
Mention examples of guidance on access to data statements provided by UK universities

### ISSUE THREAD

**Issue by MonicaDuke** [alex-ball/HowTo-CiteDatasets#4]
(Check if these are mainly about access statements rather than citation i.e. check relevance)

Bath http://www.bath.ac.uk/research/data/sharing-reuse/data-access-statement.html 

Bristol http://data.bris.ac.uk/research/using-data/

Lancaster http://www.lancaster.ac.uk/library/rdm/preserve-and-share/data-access-statements/

**Comment by alex-ball** [comment]
The Bristol page suggests using an access statement for newly collected data and data citations for third-party data. It also provides a separate [data citation guide](http://data.bris.ac.uk/files/2014/02/Citing-research-data.pdf).

The Bath page is mainly about access statements but also mentions citation; it primarily redirects people to the [DataCite guidance](https://www.datacite.org/services/cite-your-data.html).

The Lancaster page does not mention data citations.
