### ISSUE TITLE
Discuss difficulties of tracking citations and extracting citation information

### ISSUE THREAD

**Issue by MonicaDuke** [alex-ball/HowTo-CiteDatasets#9]
Based on JISCmail Research Data Management list discussion around 2-6 May 2014 (link to be tracked down and added)

**Comment by alex-ball** [comment]
Links to the discussion thread 'best practice for publication and citation of genotype datasets':
- [The original post from Alistair Miles](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1404&L=RESEARCH-DATAMAN&F=&S=&X=0E8CA1EBD3A001CB49&Y=A.BALL%40UKOLN.AC.UK&P=35004)
- [The subsequent discussion](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A1=ind1405&L=RESEARCH-DATAMAN&X=0E8CA1EBD3A001CB49&Y=A.BALL%40UKOLN.AC.UK#1)
- [The point at which the discussion turns to the issue at hand](https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=ind1405&L=RESEARCH-DATAMAN&D=0&X=0E8CA1EBD3A001CB49&Y=A.BALL%40UKOLN.AC.UK&P=4211)
